apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: demo-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: web-content
        gitRepo:
          repository: https://github.com/zawad-ux/web.git
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: demo-web
spec:
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: web
  namespace: demo-web
spec:
  to:
    kind: Service
    name: web
  port:
    targetPort: 80
